# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180907_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='roomname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
