# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_user_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_id',
            old_name='chat_id',
            new_name='chatid',
        ),
        migrations.AddField(
            model_name='chat_id',
            name='roomname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
