# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180907_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatid',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chat_id',
            name='chatid',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
