# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180907_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_id',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
